# --- !Ups

create table "rows" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "NFAItem" varchar not null,
  "FormType" varchar not null,
  "CheckCashed" long not null,
  "Approved" long not null,
);

# --- !Downs

drop table "rows" if exists;
